### ISSUE TITLE
Les sources?

### ISSUE THREAD

**Issue by pierreozoux** [fabienmoritz/seliweb#1]
Une personne me demande d'héberger ce logiciel.
Mais les sources ne sont pas dispo sur la page du projet..
Security by obscurité quoi.. ça fait peur..

Vous connaissez?

**Comment by fabienmoritz** [comment]
J'avais croisé brièvement ce projet au SEL de Lille en 2011. L'auteur du logiciel n'était pas disposé à partager les sources sans contrepartie. Techniquement, c'était déjà daté à cette époque. Vu le site web, ça n'a pas dû s'arranger. Je déconseille.
